CMS_CORE_NG/Controllers/PasswordController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ModelService;
using UserService;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace CMS_CORE_NG.Controllers
{
    public class PasswordController : Controller
    {
        private readonly IUserSvc _userSvc;

        public PasswordController(IUserSvc userSvc)
        {
            _userSvc = userSvc;
        }

        public IActionResult ResetPassword(ResetPasswordViewModel model)
        {
            return View(model);
        }

        //[ValidateAntiForgeryToken]
        [HttpPost]
        //הורדנו את ה- [FromBody]
        public async Task<IActionResult> UpdatePassword( ResetPasswordViewModel model)
        {         
            if (ModelState.IsValid)
            {                
                var result = await _userSvc.ResetPassword(model);

                if (result.IsValid)
                {                    
                    return RedirectToAction("ResetPasswordConfirmation");
                }
            }
            return BadRequest("Fail");
        }

        public IActionResult ResetPasswordConfirmation()
        {
            return View();
        }
    }
}

CMS_CORE_NG/Views/Password/ResetPassword.cshtml
@model ModelService.ResetPasswordViewModel

@{
    ViewData["Title"] = "Reset password";
}

@section Styles {

   

    <style type="text/css">

        @@font-face {
            font-family: 'ploni-bold';
            font-weight: 700;
            font-style: normal;
            src: url('fonts/aaa-fonts/webfont_files/ploni-bold-aaa.woff2') format('woff2'), url('fonts/aaa-fonts/webfont_files/ploni-bold-aaa.woff') format('woff');
        }

        @@font-face {
            font-family: 'ploni';
            font-weight: 400;
            font-style: normal;
            src: url('fonts/aaa-fonts/webfont_files/ploni-regular-aaa.woff2') format('woff2'), url('fonts/aaa-fonts/webfont_files/ploni-regular-aaa.woff') format('woff');
        }

        html,
        body {
            font-family: 'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;
            direction: rtl;
            text-align: center;
            background: #19294d;
        }
        .sec-wrapper {
            background: #fff;
            padding: 1.5rem;
            border: 1px solid #eaecec;
            box-shadow: 0 2px 2px rgba(0, 0, 0, 0.1);
            border-radius: 2rem;
            max-width: 500px;
            margin: 5% auto 14px;
        }


        .form-control {
            margin: 1rem 0;
            width: 27rem;
            border-radius: 0.5rem;
            color: #324148;
            border:1px black solid;
            padding: 0.375rem 0.75rem;
            height: calc(2.25rem + 4px);
          
        }

            .form-control:focus {
                background-color: #04e6e01a;
                border: 1px solid #04e6e0 !important;
                border-radius: 7px;
                opacity: 1;
            }

        .register-logo {
            margin-bottom: 1.75rem;
            margin-top: 1.75rem;
            color: #000;
            font-size: 1.5rem;
            text-align: center;
        }

        .underline {
            border-bottom: 1px dotted black;
            position: relative;
            display: inline-block;
        }

            .underline:hover .wordTool {
                visibility: visible;
                opacity: 1;
            }

            .underline .wordTool::after {
                content: "";
                position: absolute;
                top: 100%;
                left: 50%;
                margin-left: -5px;
                border-width: 5px;
                border-style: solid;
                border-color: #555 transparent transparent transparent;
            }

        button {
            font-family: 'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;
            background-color: #373cf5;
            color: #fff;
            border: 1px solid #373cf5;
            cursor: pointer;
            margin-top:1rem;
        }

        .underline .wordTool {
            visibility: hidden;
            width: 200px;
            background-color: #555;
            color: #fff;
            text-align: center;
            border-radius: 6px;
            padding: 5px 0;
            position: absolute;
            z-index: 1;
            bottom: 125%;
            left: 50%;
            margin-left: -60px;
            opacity: 0;
            transition: opacity 0.3s;
        }
    </style>
}
<div class="background">
<div class="sec-wrapper">
    <div class="container">
        <div class="reset-password mb-5">
            @Html.AntiForgeryToken()
            <div class="register-logo mb-3">
                <a href="https://www.techhowdy.com" border="0" style="border: none; text-decoration: none; color: #19294D;  font-size: 2rem; font-weight: bold;">אתחול סיסמה</a>
            </div>
            <form method="post" id="resetPasswordForm" name="resetPasswordForm" action="@Url.Action("UpdatePassword","Password")">
                <input asp-for="Code" type="hidden" />
                <div class="form-group">
                    @*<label asp-for="Email">מייל</label>*@
                    <input asp-for="Email" id="email" type="email" class="form-control" placeholder="Windo!1@gmail.com" />
                    @*<span asp-validation-for="Email" id="emailValidation" class="text-danger"></span>*@
                </div>
                <div class="form-group has-feedback">
                    @*<label asp-for="Password">סיסמה</label>*@
                    <input asp-for="Password" id="password" type="password" class="form-control" placeholder="סיסמה חדשה" />
                    @*<span asp-validation-for="Password" id="passValidation" class="text-danger"></span>*@
                </div>
                <div class="form-group has-feedback">
                    @*<label asp-for="ConfirmPassword">אימות סיסמה</label>*@
                    <input asp-for="ConfirmPassword" id="cpassword" type="password" class="form-control" placeholder="**********" />
                    @*<span asp-validation-for="ConfirmPassword" id="cpassValidation" class="text-danger"></span>*@
                </div>
                <div class="text-center mt-3">
                    <button type="submit" id="submit" class="btn btn-primary btn-flat" style="padding: 0.75rem; border-radius: 30px; min-width: 150px;  font-weight: bold;">עדכנו את הסיסמה שלי</button>
                </div>
            </form>

            @*<div class="border p-2">
                    <p class="pl-2"><i class="fas fa-star mr-2 text-danger"></i> לפחות אות גדולה אחת באנגלית</p>
                    <p class="pl-2"><i class="fas fa-star mr-2 text-danger"></i> לפחות אות קטנה אחת באנגלית</p>
                    <p class="pl-2">
                        <i class="fas fa-star mr-2 text-danger"></i>
                        לפחות ספרה אחת
                    </p>
                    <p class="pl-2">
                        <i class="fas fa-star mr-2 text-danger"></i>
                        לפחות תו מיוחד אחד
                    </p>
                    <p class="pl-2">
                        <i class="fas fa-star mr-2 text-danger"></i>
                        אורך מינימלי של שמונה תווים
                    </p>
                </div>*@
            <div>
                <p>הסיסמה שלך צריכה לכלול:  ספרה,<span class="underline">תו מיוחד<span class="wordTool">!)(-_]}[{?. < ~=/ | &amp;&and;&frasl;&Iota;&lowast; </span></span> ,אות קטנה באנגלית, אות גדולה באנגלית לדוגמה:!Windo1</p>
            </div>
            <div class="text-center mt-3">
                <a id="home" href="/" class="btn btn-success btn-flat text-white" style="min-width: 150px ; padding-bottom:3px;">חזרה לדף הבית</a>
            </div>
        </div>
    </div>
</div>
</div>

@section Scripts {
    <script src="~/lib/custom/js/account/forgot-password.min.js">
    </script>
    @await Html.PartialAsync("_ValidationScriptsPartial")


}

CMS_CORE_NG/Views/Password/ResetPasswordConfirmation.cshtml
@model ModelService.ResetPasswordViewModel

@{
    ViewData["Title"] = "Reset password confirmation";
}

@section Styles {

    
}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
    <style type="text/css">

        @@font-face {
            font-family: 'ploni-bold';
            font-weight: 700;
            font-style: normal;
            src: url('../fonts/aaa-fonts/webfont_files/ploni-bold-aaa.woff2') format('woff2'), url('../fonts/aaa-fonts/webfont_files/ploni-bold-aaa.woff') format('woff'), url('../../fonts/aaa-fonts/webfont_files/ploni-bold-aaa.woff') format('truetype');
        }

        @@font-face {
            font-family: 'ploni';
            font-weight: 400;
            font-style: normal;
            src: url('../fonts/aaa-fonts/webfont_files/ploni-regular-aaa.woff2') format('woff2'), url('../fonts/aaa-fonts/webfont_files/ploni-regular-aaa.woff') format('woff'), url('../../fonts/aaa-fonts/webfont_files/ploni-bold-aaa.woff') format('truetype');
        }

        html,
        body {
            font-family: "ploni" sans-serif !important;
            direction: rtl;
            text-align: center;
            background: #19294d;
        }

        .sec-wrapper {
            background: #fff;
            padding: 2rem;
            border: 1px solid #eaecec;
            box-shadow: 0 2px 2px rgba(0, 0, 0, 0.1);
            border-radius: 2rem;
            max-width: 500px;
            margin: 5% auto 14px;
            text-align: center;
            height: 35vh;
            width: 45vw;
            box-shadow: 0 4px 8px 4px rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
        }



        h2 {
            font-size:3rem;
            margin-top: 1.5rem;
            font-family: 'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;
            color: #19294D;
            font-weight: bold;
        }

        p {
            font-family: 'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;
            font-size: 1.5rem;
        }

        .btn {
            margin-top: 2rem;
            border-radius: 30px;
            background-color: #373cf5;
            color: white;
            font-weight: bold;
            padding: 0.8rem 2.5rem;
            border: none;
            font-family: 'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;
        }
        a{
            text-decoration:none;
            color:white;
        }

        .x {
            float: left;
        }
    </style>
</head>

<body>
    <div class="sec-wrapper">
        @*<img (click)="close()" class="x" src="../../CMS_CORE_NG/ClientApp/src/assets/icons/x.png" class="icon_s" alt="סגירת מודעה" />*@
        <div class="white-box" style="text-align:center">
            <h2>הצליח לך!</h2>
            <p> הסיסמה החדשה שלך נשמרה בהצלחה.</p>
            <button class="btn"><a href="/">היכנסי לאתר</a></button>
        </div>
    </div>
</body>

</html>